<?php

define(ROOT_DIR, "~/Documents" . DIRECTORY_SEPARATOR);
define(CLASS_DIR, "csc490" . DIRECTORY_SEPARATOR);
define(PROJECT_DIR, "CSC490Project" . DIRECTORY_SEPARATOR);
define(SOURCE_DIR, "src" . DIRECTORY_SEPARATOR);
define(HOME_LOCATION, ROOT_DIR . CLASS_DIR . PROJECT_DIR . SOURCE_DIR . DIRECTORY_SEPARATOR);
define(CONFIG_DIR, HOME_LOCATION . "config" . DIRECTORY_SEPARATOR);
define(MODEL_LOCATION, HOME_LOCATION . "model" . DIRECTORY_SEPARATOR);
define(CONTROLLER_LOCATION, HOME_LOCATION . "controller" . DIRECTORY_SEPARATOR);
define(VIEW_LOCATION, HOME_LOCATION . "view" . DIRECTORY_SEPARATOR);
define(HOME_VIEW, VIEW_LOCATION . "home" . DIRECTORY_SEPARATOR);